version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: todo-app-full       # ビルド済みのマルチステージイメージ名
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todoapp
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Tokyo"
    volumes:
      - ./logs:/app/logs   # ← これを追加すると、コンテナ内/app/logsがホストの./logsと同期

volumes:
  pgdata:
